# docker-compose.yml
version: "3.1"

services:
  db:
    image: postgres:latest
    container_name: auth-next
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth-next
    ports:
      - "5432:5432"
